name: 'User Activity Report'
on:
  workflow_dispatch:
  
jobs:
  'create-report':
    runs-on: ubuntu-latest
    steps:
      - uses: sorekz/user-activity-report@v1
        with:
          token: ${{ secrets.METRICS_REPORT }}
          organization: 'OpenHUTB'
          create-json: data.json
          create-csv: data.csv

      - uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            data.json
            data.csv